# -*- coding: utf-8 -*-
"""Smart_Meter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uFTd6XiZPdTlEnCMdc078zJEPlXwOGr5
"""

# Step 1: Upload Kaggle API Key
from google.colab import files
files.upload()

# Step 2: Install Kaggle API
#!pip install kaggle

# Step 3: Move kaggle.json to the correct directory
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Step 4: Download the London Smart Meter dataset
!kaggle datasets download -d jeanmidev/smart-meters-in-london

# Step 5: Unzip the dataset
!unzip -o smart-meters-in-london.zip daily_dataset.csv

# Step 6: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping

# Step 7: Load the Daily Dataset
daily_data = pd.read_csv('daily_dataset.csv', nrows=200000)
daily_data = daily_data.sample(frac=0.5, random_state=42)

# Display the first few rows of the dataset
daily_data.head()

daily_data.columns

# Step 8: Prepare Data for Training
daily_data['day'] = pd.to_datetime(daily_data['day'], format='%Y-%m-%d')  # Adjust format if necessary
daily_data.set_index('day', inplace=True)

# Step 9: Feature Engineering
daily_data['Year'] = daily_data.index.year
daily_data['Month'] = daily_data.index.month
daily_data['DayOfWeek'] = daily_data.index.dayofweek

daily_data['energy_mean'] = daily_data['energy_mean'].fillna(daily_data['energy_mean'].mean())

# Step 10: Prepare Data for Training
X = daily_data[['Year', 'Month', 'DayOfWeek']]
y = daily_data['energy_mean']  # Using energy_mean as the target variable

# Step 11: Feature Scaling
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

# Step 12: Build the Deep Learning Model
model = Sequential([
    Dense(64, activation="relu", input_shape=(X_train.shape[1],)),
    Dense(32, activation="relu"),
    Dense(1)   # regression output
])

model.summary()

print(daily_data.isnull().sum())
print(np.any(np.isnan(X_train)), np.any(np.isnan(y_train)))

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Step 13: Train the Model
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# history = model.fit(
#     X_train, y_train,
#     epochs=5, batch_size=16,
#     validation_split=0.2,
#     callbacks=[early_stop]
# )
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=10,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

# Step 14: Make Predictions
y_pred = model.predict(X_test).flatten()

# Step 15: Evaluate the Model
mse = np.mean(np.square(y_test, y_pred))
print(f'Mean Squared Error: {mse:.4f}')

# Step 16: Plotting the Results
#(A) Loss curve
plt.figure(figsize=(6,4))
plt.plot(history.history["loss"], label="Train Loss")
plt.plot(history.history["val_loss"], label="Val Loss")
plt.xlabel("Epochs")
plt.ylabel("MSE Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.show()

# (B) Scatter plot (ideal line y=x)
plt.figure(figsize=(6,6))
plt.scatter(y_test, y_pred, alpha=0.5)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()], 'r--')
plt.xlabel("Actual Energy Consumption")
plt.ylabel("Predicted Energy Consumption")
plt.title("Actual vs Predicted")
plt.show()

# (C) Line plot (first 200 points)
y_test_smooth = pd.Series(y_test.values[:200]).rolling(window=5).mean()
y_pred_smooth = pd.Series(y_pred[:200]).rolling(window=5).mean()

plt.figure(figsize=(12,6))
plt.plot(y_test_smooth, label="Actual (Smoothed)", color="blue")
plt.plot(y_pred_smooth, label="Predicted (Smoothed)", color="red")
plt.xlabel("Sample Index")
plt.ylabel("Energy Consumption (Mean)")
plt.title("Actual vs Predicted (Smoothed)")
plt.legend()
plt.show()

# Step 17: Save Model for Deployment
model.save('final_model.keras')
print("Model saved successfully!")